Move human_in_the_loop.py example to zoo
huawei-noah/SMARTS pull request #1226
Opened 2022-01-06 18:19 UTC by qianyi-sun

#1220

2022-01-06 21:28 UTC, Gamenot commented
You will want to run `black` formatting.

2022-01-06 21:33 UTC, Gamenot requested changes
You will need to list this agent in `zoo/policies/__init__.py`.

2022-01-06 21:33 UTC, Gamenot commented on zoo/evaluation/human_in_the_loop.py
> +    from examples.argument_parser import default_argument_parser
This import should be removed.

2022-01-06 21:33 UTC, Gamenot commented on zoo/evaluation/human_in_the_loop.py
>  else:
Also this import.

2022-01-10 20:08 UTC, Gamenot commented
Please run `black`.

2022-01-10 21:56 UTC, qianyi-sun commented
> Please run `black`.
reformatted

2022-01-11 02:37 UTC, Gamenot approved these changes
What is left is nitpick that is not blocking but good to clean up.

2022-01-11 02:37 UTC, Gamenot commented on zoo/policies/human_in_the_loop.py
>  AGENT_ID = "Agent-007"
These lines can be removed as well.
```suggestion
```

2022-01-11 02:37 UTC, Gamenot commented on zoo/policies/human_in_the_loop.py
>  from smarts.core.utils.episodes import episodes
This import can also be removed.
```suggestion
```

Please also remove the `gym` and `logging` imports.

2022-01-11 16:26 UTC, RutvikGupta approved these changes

2022-01-11 18:12 UTC, merged