Develop
huawei-noah/SMARTS pull request #1499
Opened 2022-07-11 21:09 UTC by AisenGinn

Added gif_recorder.py and recorder_wrapper.py into smarts.env.wrappers folder for video recording function.

2022-07-14 20:29 UTC, Gamenot requested changes
Please also remove the `SMARTS` submodule included in this branch.

2022-07-14 20:29 UTC, Gamenot commented on smarts/env/wrappers/gif_recorder.py
> +        self.dir = dir
An improvement I could suggest is to add a timestamp or `uuid` component to the directory so there is less likelihood of collisions if there are multiple of these running.

2022-07-14 20:29 UTC, Gamenot commented on smarts/env/wrappers/gif_recorder.py
> +        image = self.env.render(mode="rgb_array")
There are three directions we could go with this, we can keep as is:

```suggestion
    def capture_frame(self, step_num):
        image = self.env.render(mode="rgb_array")
```

We can remove `self.env` and pass in the environment on render:

```suggestion
    # pass in env
    def capture_frame(self, step_num, env):
        image = env.render(mode="rgb_array")
```

or we could only pass in the image (my preference):

```suggestion
    # elsewhere call 
    # > `gif_recorder.capture_frame(
    # >     get_next_id(),
    # >     env.render(mode="rgb_array"),
    # > )  
    def capture_frame(self, step_num, image):
```

2022-07-14 20:29 UTC, Gamenot commented on smarts/env/wrappers/recorder_wrapper.py
> +        self.gif_recorder.close_recorder()
```suggestion
    def __del__(self):
        self.close()
```

2022-07-14 20:29 UTC, Gamenot commented on smarts/env/wrappers/recorder_wrapper.py
> +        self.gif_recorder.close_recorder()
I could recommend removing `close_recorder()` and just moving the `gif` generation to here.

```suggestion
    def close(self):
        if self.gif_recorder is not None:
            self.gif_recorder.generate_gif()
            self.gif_recorder.close_recorder()
            self.gif_recorder = None
            self.recording = False
```

2022-07-27 17:51 UTC, Gamenot approved these changes

2022-08-23 20:11 UTC, Gamenot commented
@AisenGinn Please bug people to review this so it does not sit too long.

2022-11-15 19:10 UTC, saulfield requested changes

2022-11-15 19:10 UTC, saulfield commented on smarts/env/wrappers/gif_recorder.py
> +            clip.write_gif(f"videos/{self._dir_name}.gif")
Should this be relative to `self.dir` as well?

2022-11-15 19:10 UTC, saulfield commented on smarts/env/wrappers/recorder_wrapper.py
> +            os.mkdir("videos")
Same feedback about the try/catch here. Also, I think this directory should be explicit about where it is created.

2022-11-17 21:56 UTC, Gamenot requested changes
One set of issues to figure out. Good Work!

2022-11-17 21:56 UTC, Gamenot commented on smarts/env/wrappers/gif_recorder.py
> +    )
I think my last concern here is that this `try/catch` swallows the import error. I think we still want to raise an error here. Aside from that we should not expect that the user is working from a dev platform.
```suggestion
try:
    from moviepy.editor import ImageClip, ImageSequenceClip
except (ImportError, ModuleNotFoundError):
    logging.warning(sys.exc_info())
    logging.warning(
        "You may not have installed the [gym] dependencies required to capture the video. Install them first with the `smarts[gym]` extras."
    )
    raise
```

2022-11-17 22:38 UTC, saulfield approved these changes

2022-11-21 21:43 UTC, Gamenot approved these changes
Good work!

2022-11-21 21:43 UTC, merged