Fixed iss1587 smarts simulation crash
huawei-noah/SMARTS pull request #1673
Opened 2022-10-18 14:31 UTC by AisenGinn

This PR attempt to fix iss1587(smarts simulation crash when agent is far off road). Currently the `lookahead` in `smarts.core.road_map.curevature_radius_at_offset` only accept `lookahead>=1`, but `lookahead` is calculated by `lookahead = math.ceil(1 + math.log(self._target_speed))` in `smarts.core.local_traffic_provider._slow_for_curves`. The error will occur when the `self.target_speed` is very small which make the ` math.log(self._target_speed)<-1`. This will cause `lookahead` to be negative and thus raise the assertion error. I added code that set `lookahead` to be 1 when it is negative due to small `self.target_speed` which ensure the `smarts.core.road_map.curevature_radius_at_offset`  doesn't raise assertion error.
The test_agent is about to drive off road in loop scenario, the loop scenario is setup to use the smarts traffic_local_provider.py to provide traffic. 
You can use following command to test the test_agent in loop scenario after installing required dependencies:
`scl scenario build --clean scenarios/sumo/loop`
`scl run --envision examples/test_agent.py scenarios/sumo/loop`

2022-10-26 18:03 UTC, Gamenot requested changes
Some changes are needed.

2022-10-26 18:03 UTC, Gamenot commented on smarts/core/local_traffic_provider.py
> +            lookahead = 1
```suggestion
        lookahead = math.ceil(1 + math.log(self._target_speed))
        lookahead = max(1, lookahead)
```

2022-10-26 18:03 UTC, Gamenot commented on scenarios/sumo/loop/scenario.py
> +    engine="SMARTS"
We should not change this. Please remove the `SMARTS` traffic backing here.

2022-10-26 18:03 UTC, Gamenot commented on examples/test_agent.py
> +import logging
Please remove this file.

2022-11-04 17:48 UTC, Gamenot approved these changes

2022-11-11 20:17 UTC, saulfield approved these changes

2022-11-14 18:18 UTC, merged