Fix Envision visualization issue in "near real time" mode
huawei-noah/SMARTS pull request #1766
Opened 2022-12-02 19:59 UTC by qianyi-sun

2022-12-02 20:59 UTC, saulfield commented on envision/web/src/components/simulation.js
> +          let delt_elapsed_time_in_sec = msInSec * (elapsed_times[0] - prevElapsedTime);
This is in milliseconds I believe. Also, I think the style is snakeCase (even though not everything here follows it).
```suggestion
          let deltaElapsedMs = msInSec * (elapsed_times[0] - prevElapsedTime);
```

2022-12-02 20:59 UTC, saulfield commented on envision/web/src/components/simulation.js
> +            delt_elapsed_time_in_sec = 100
After using Python, it's easy to forget about semicolons. Though not always necessary in js, they should be used to make sure statements stay separate from each other.
```suggestion
            delt_elapsed_time_in_sec = 100;
```

2022-12-02 21:23 UTC, Gamenot requested changes
Please add a changelog entry.

2022-12-06 17:36 UTC, Gamenot commented on CHANGELOG.md
> +- Added "SMARTS Performance Benchmark" development tool for evaluating the simulation performance.
Where did this entry come from?

2022-12-06 21:53 UTC, merged