Replace scipy
huawei-noah/SMARTS pull request #2071
Opened 2023-06-23 17:05 UTC by saulfield

Removes `scipy` as a core package dependency and makes progress towards #1981.

2023-06-23 21:02 UTC, Gamenot requested changes

2023-06-23 21:39 UTC, saulfield commented on smarts/core/lanepoints.py
> +        closest_indices = np.argsort(dists)[:k]
Yes, it is roughly the same as using the KDTree. The frame time seems to be dominated by other things.

2023-06-23 21:40 UTC, saulfield commented on smarts/core/lanepoints.py
> +        self._lp_points_by_edge_id = {
Yes, there is a slight performance gain on smaller maps from this change.

2023-06-28 04:07 UTC, Adaickalavan approved these changes

2023-06-28 21:54 UTC, Gamenot approved these changes

2023-06-28 21:59 UTC, merged