Add route waypoints in RoadWaypoints
huawei-noah/SMARTS pull request #306
Opened 2020-12-12 03:43 UTC by liamchzh

2020-12-14 19:01 UTC, Gamenot requested changes
Some commments.

2020-12-15 00:29 UTC, Gamenot approved these changes

2020-12-15 00:51 UTC, aurorahcx approved these changes

2020-12-15 00:54 UTC, liamchzh commented on smarts/core/sensors.py
> +                waypoints_with_task = self._mission_planner.uturn_waypoints(
Won't address it for now.

2020-12-15 00:57 UTC, liamchzh commented on smarts/core/sensors.py
> +        if waypoints_with_task:
Actually `if waypoints_with_task` was my intention, waypoints_with_task can either be `None` or `[]`.

2020-12-15 01:03 UTC, liamchzh commented on smarts/core/sensors.py
> +    route_waypoints: List[Waypoint]
@mg2015started

2020-12-15 02:34 UTC, merged