WIP fix collesion between agent and bubble agent vehicle
huawei-noah/SMARTS pull request #485
Opened 2021-01-27 00:10 UTC by JingfeiPeng

2021-01-27 00:11 UTC, JingfeiPeng commented on smarts/core/vehicle_index.py
> +        print(f"Before: {agent_id} action: {interface}") # interfce none here
interface is None here

2021-01-27 00:11 UTC, JingfeiPeng commented on smarts/core/bubble_manager.py
> +        print(f"After: {agent_id} action: {interface.action}")
Interface is not none and can access the action

2021-01-27 01:52 UTC, Gamenot commented
OK, I took a look at this and from what I can see it is a problem with using the TargetPose action space here.

2021-01-29 20:47 UTC, JingfeiPeng commented
Smarts will only call controller's perform_action if the agent's action is in _dynamic_action_spaces.

We want the vehicle to have boxChassis so vehicle index.py, switch_control_to_agent check if agent's action is not in _dynamic_action_spaces and if so, create BoxChassis

To let the vehicle to reach the controller's perform_action method, we need to put TargetPose in dynnamic_action_spaces....

This causes vehicle index switch_control_to_agent to not create box model for the agents, and have the TargetPose agents to use AckermanChassis. Though this can be solved by making vehicle Index check if agent action is TargetPose or Multi-targetpose.

@Gamenot  But it seems the controllers are for vehicles with Ackerman chassis, and using MotionPlannerProvider for bubble agents with BoxChassis is that not bad of a choice?

2021-02-01 18:46 UTC, JingfeiPeng commented
Finished ensuring collision issue is fixed and proper use of boxChassis for non dynamic agents.
Will create another issue for refactoring MotionPlannerProvider into a controller similar to Trajectory_Tracking controller

2021-02-01 22:35 UTC, Gamenot approved these changes

2021-02-01 22:35 UTC, Gamenot commented on smarts/core/vehicle.py
> +    def _warn_non_kinematic_vehicle_set_pose(self):
This was a bad naming scheme on my part. Also not called.

2021-02-01 22:35 UTC, Gamenot commented on smarts/core/vehicle.py
>      def set_pose(self, pose: Pose):
I think here ^.

2021-02-01 22:39 UTC, Gamenot requested changes

2021-02-01 22:39 UTC, Gamenot commented on smarts/core/chassis.py
> +        contact_points = _query_bullet_contact_points(self._client, self.bullet_id, -1)
```suggestion
        contact_points = _query_bullet_contact_points(self._client, self._bullet_body.bullet_id, -1)
```

2021-02-01 22:41 UTC, Gamenot approved these changes

2021-02-02 16:46 UTC, iman512003 approved these changes

2021-02-02 17:02 UTC, merged