Add collapsible debug panel display agent info
huawei-noah/SMARTS pull request #580
Opened 2021-02-12 20:18 UTC by JingfeiPeng

Added a left control panel on envision to select what information to display. 

https://user-images.githubusercontent.com/36685292/107818087-0e003e00-6d45-11eb-8438-da764e5e6814.mp4

2021-02-17 20:00 UTC, Gamenot approved these changes

2021-02-17 20:26 UTC, JingfeiPeng commented on smarts/core/smarts.py
> +                ):
I haven't encounter any cases when this is not true, This is only not true if vehicle has no way points.
When this is not true, the default on js side is an empty dict which is ok.

2021-02-17 20:59 UTC, Gamenot requested changes
Testing on my side I found that the toggle works for turning on but not off. Could you confirm it works as expected on your side?

2021-02-17 21:15 UTC, JingfeiPeng commented
> Testing on my side I found that the toggle works for turning on but not off. Could you confirm it works as expected on your side?
Right... I also met this issue sometimes. When I was testing the debug panel on the development version it always works for on and off. Then if I use the build version it has a high chance that the panel doesn't work for turning off  on the first time the page loads. But if I refresh the page and check again it works again for turning on and off.

2021-02-17 21:47 UTC, JingfeiPeng commented
There was an error when toggling the control using checkbox (the other way is to click on the text). Fixed this now.

2021-02-17 22:03 UTC, Gamenot approved these changes
LGTM :shipit:

2021-02-17 23:53 UTC, Adaickalavan commented
In my testing, the sidebar does appear in Mozilla Firefox browser, but does not appear in Google Chrome browser.

2021-02-18 00:10 UTC, JingfeiPeng commented
@Adaickalavan I see. I think it is because Chrome caches website files, if you see "Show Scores" on the top right besides "egocentric view" then it is probably the case. [https://www.google.com/search?q=chrome+clear+website+cache&oq=chrome+clear+web&aqs=chrome.0.0j69i57j0l2j0i22i30l4.7362j0j7&sourceid=chrome&ie=UTF-8](url) this should clear old the website files. I just tested on chrome the debug panel showed up.

2021-02-18 00:41 UTC, Adaickalavan approved these changes

2021-02-18 02:00 UTC, merged