Issue 68: ogm/drivable area are blank in the first few steps of agents
huawei-noah/SMARTS pull request #83
Opened 2020-10-27 22:28 UTC by aurorahcx

2020-10-27 22:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/huawei-noah/SMARTS?pullRequest=83) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/huawei-noah/SMARTS?pullRequest=83) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: JVillella<br/>:x: aurorah<br/><hr/>**aurorah** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/huawei-noah/SMARTS?pullRequest=83) it.</sub>

2020-10-28 02:30 UTC, JVillella commented
We do _not_ want to be re-introducing the task manager at the sensor level. This was intentionally removed because it's a leaky abstraction. Furthermore, it complicates our step loop. We now have code that operates out of flow of the top-level loop.

Did you try the solution we were brainstorming as a team? If that's not working could you share why and we can consider another approach?

2020-10-28 02:31 UTC, JVillella requested changes
We do not want to be re-introducing the task manager at the sensor level. This was intentionally removed because it's a leaky abstraction. Furthermore, it complicates our step loop. We now have code that operates out of flow of the top-level loop.

Did you try the solution we were brainstorming as a team? If that's not working could you share why and we can consider another approach?

2020-10-28 03:03 UTC, aurorahcx commented on smarts/core/smarts.py
> +
This is the change we brainstormed as a team, I thought we agreed that we had to use task manager to be able to synch update and render threads per frame?
If we do not use task manager to synch per frame, there can be mismatch across multiple steps.
@JVillella

2020-10-28 03:44 UTC, Gamenot commented
I never did figure out why the resources were not cleaned up. Perhaps it is the use of `partial()` here? If `panda3d` for some reason assumes that it needs to cache some methods it might not clean up the camera reference.

2020-10-28 13:24 UTC, aurorahcx commented
> I never did figure out why the resources were not cleaned but that the task manager was involved. Perhaps it is the use of `partial()` here? If `panda3d` for some reason assumes that it needs to cache some methods it might not clean up the camera reference in the task manager even after calling to remove the task.
> 
> Edit:
> 
> ![image](https://user-images.githubusercontent.com/8764693/97388924-8be02c80-18af-11eb-8056-f6968dc9dcbd.png)
> 
> Otherwise it might have to do with the fact that the task manager is a global object.

Is this SMARTS code?

2020-10-29 14:16 UTC, Gamenot commented
Please also check that window resources are not leaking before merging this PR.

I did so before by using  `xwininfo -root -children | wc -l` or `xrestop`.

2020-10-29 17:26 UTC, aurorahcx commented
> We do not want to be re-introducing the task manager at the sensor level. This was intentionally removed because it's a leaky abstraction. Furthermore, it complicates our step loop. We now have code that operates out of flow of the top-level loop.
> 
> Did you try the solution we were brainstorming as a team? If that's not working could you share why and we can consider another approach?
> 
> (EDIT: Meant to request changes, not close)

Sorry I misunderstood, I thought I had to add back the task manager at the sensor level to make `self.taskMgr.mgr.poll()` work in smarts.py, I realized I don't need it to do this later. I will close this PR and open a new one.

2020-10-29 17:30 UTC, closed without merging